### ISSUE TITLE
Ability to attach behavior to a bubble world

### ISSUE THREAD

**Issue by Gegy** [NucleoidMC/fantasy#1]
This could involve replacements of chunk tracking, sending a resource pack, changing world saving logic or similar, where each would be handled by a specific instance of some behavior modifying type. 

This might want to interact with https://github.com/NucleoidMC/plasmid/issues/104 which would split out Plasmid's events and rules into their own library.

**Comment by Patbox** [comment]
Fantasy now allows to create worlds using custom classes (as long as they extend RuntimeWorld), allowing for more customization.
