### ISSUE TITLE
Custom seed not working

### ISSUE THREAD

**Issue by Unreal852** [NucleoidMC/fantasy#14]
Hello, i'm using this lib to create persistent worlds but there is a catch, the seed i set in the RuntimeWorldConfig is being ignored and all the worlds i create are using the same seed as my overworld instead of my custom one.
I'm using Minecraft 1.19.2 and Fantasy 0.4.6+1.19.2

**Comment by PinkGoosik** [comment]
you can pass seed directly to chunk generator with **ChunkGenerator#withSeed(seed)**
![image](https://user-images.githubusercontent.com/56874042/185410696-3fa01be5-aa1b-4460-ba37-d8632c1ce146.png)

**Comment by Unreal852** [comment]
With which version do you do that ? i don't have the withSeed 1.12.2

**Comment by PinkGoosik** [comment]
oh damn it's 1.18.2
