### ISSUE TITLE
Custom seed isn't applied to Fantasy world

### ISSUE THREAD

**Issue by HyperPigeon** [NucleoidMC/fantasy#19]
I've been trying to create a copy of the Overworld dimension using Fantasy. 

```
       Long seed = gameSpace.getServer().getOverworld().getRandom().nextLong();        
       ChunkGenerator overworldGen = config.overworld().chunkGenerator();

        RuntimeWorldConfig worldConfig = new RuntimeWorldConfig()
                .setDimensionType(config.overworld().dimensionTypeEntry())
                .setDifficulty(Difficulty.HARD)
                .setGameRule(GameRules.DO_MOB_SPAWNING,true)
                .setGameRule(GameRules.DO_DAYLIGHT_CYCLE, true)
                .setGenerator(overworldGen)
                .setSeed(seed);
```

However, the world created by the above `RuntimeWorldConfig` is always the same regardless of the `seed` value. My guess is that the game is using the seed of the main world instead of the set seed.

**Comment by HyperPigeon** [comment]
That's a bit irritating, does that mean I have to make my own generator?

**Comment by Patbox** [comment]
Most likely

**Comment by haykam821** [comment]
The main issue is that the runtime world must return the custom seed through `World#getSeed`, including within the `ServerWorld` constructor. The solution is to override `World#getSeed` in a way that the seed is initialized before it is called.

**Comment by SakuraWald** [comment]
> 

Spent hours debugging and finally found this solution.
