### ISSUE TITLE
1.20.1 Release?

### ISSUE THREAD

**Issue by LaylaMeower** [NucleoidMC/fantasy#36]

**Comment by Patbox** [comment]
Use [v0.4.11+1.20-rc1](https://github.com/NucleoidMC/fantasy/releases/tag/v0.4.11%2B1.20-rc1)

**Comment by LaylaMeower** [comment]
> Use [v0.4.11+1.20-rc1](https://github.com/NucleoidMC/fantasy/releases/tag/v0.4.11%2B1.20-rc1)

Oh, alright. Does it also support 1.20.2, btw?

**Comment by Patbox** [comment]
From what I know it should, but if not feel free to make an new issue
