### ISSUE TITLE
[Request] Default biome when creating new dimension

### ISSUE THREAD

**Issue by Aareon** [NucleoidMC/fantasy#48]
Not sure if it's feasible, but if it would be possible, can there be a method to set a specific biome for a dimension? Or if anyone has any guidance as to how to make something like this works. All input is appreciated!

**Comment by Aareon** [comment]
Thanks @begrs I'll check it out!

**Comment by begrs** [comment]
update: it works perfeclty using it as I suggested. My issue was that for some reason a player joining a temporary dimension from the start, still had the overworld loaded in client side.

**Comment by begrs** [comment]
@Aareon please close the issue if it worked for you too :)
