### ISSUE TITLE
CurseForge

### ISSUE THREAD

**Issue by Hozq** [NucleoidMC/fantasy#9]
Hello, gonna get straight to the point here; this dependency doesn't exist on CurseForge which in turn removes our ability to use mods that use Fantasy to work since our server host only takes mods from CurseForge and you aren't able to upload your own mods to your server.

Making Fantasy available on CurseForge would be very appreciated.
(I couldn't find a place to comment so that's why its under Issues)

**Comment by Patbox** [comment]
These mods should just bundle  Fantasy with their jar. Thats intended usage of it. You can ask modders using it to do so

**Comment by LoganDark** [comment]
> Thats intended usage of it.

You should probably change the README then, to use something like this:

```groovy
	include(modImplementation('xyz.nucleoid:fantasy:FANTASY_VERSION'))
```

(yes this works)
